"""Regenerate docs/COPY_PASTE_BUNDLE.md: every project file in one Markdown document,
each in its own code block headed by its exact path. Run: python scripts/build_bundle.py"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "COPY_PASTE_BUNDLE.md"
SKIP_DIRS = {"__pycache__", ".pytest_cache", ".venv", "venv", "data", "exports"}
LANG = {".py": "python", ".json": "json", ".md": "markdown", ".sql": "sql", ".txt": "text", ".ini": "ini",
        ".xml": "xml", ".idx": "text", ".yml": "yaml", ".example": "bash", ".gitignore": "text"}


def files():
    for path in sorted(ROOT.rglob("*")):
        rel = path.relative_to(ROOT)
        if path.is_dir() or any(p in SKIP_DIRS for p in rel.parts) or path == OUT or path.suffix == ".db":
            continue
        yield rel


def main():
    parts = ["# Discovery Engine: copy-paste bundle\n",
             "Every file of `discovery-engine/`, each with its exact path. Create each file at that path "
             "(relative to your repository root) and paste the block contents. Generated by "
             "`scripts/build_bundle.py`; the files in the repository are the source of truth.\n",
             "## File list\n"]
    rels = list(files())
    parts += [f"- `discovery-engine/{r.as_posix()}`" for r in rels]
    for rel in rels:
        text = (ROOT / rel).read_text(encoding="utf-8")
        lang = LANG.get(rel.suffix or rel.name, "text")
        fence = "````" if "```" in text else "```"
        parts.append(f"\n## `discovery-engine/{rel.as_posix()}`\n\n{fence}{lang}\n{text.rstrip()}\n{fence}\n")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rels)} files)")


if __name__ == "__main__":
    main()
